/* Journey data — Mukun Verma
   Framed from her own Instagram voice: wandering, devotion, human connection.
*/

const JOURNEY = [
  {
    id: 'rishikesh',
    order: 1,
    place: 'Rishikesh',
    region: 'Uttarakhand · where the bowl was first placed in her hands',
    coords: [30.0869, 78.2676],
    season: 'The Source',
    year: '2019 — 2023',
    practice: 'Hatha · Sound Healing · Master Certification',
    element: 'Ganga — water, current, surrender',
    bowl: 'Root',
    lat: '30°05\u2032 N',
    lon: '78°16\u2032 E',
    altitude: '372 m',
    quote: 'The river does not hurry, and still it arrives.',
    story: 'Where the Ganges leaves the mountains and meets the plain, she first learned to sit still. Years later, she returned to this same soil to receive her Master Sound Healing certification at the Himalayan Healing School — the bowl, at last, placed into her own hands to carry forward.',
    offerings: ['200-hr foundation', 'Master Sound Healing certification', 'Himalayan Healing School'],
    img: 'assets/rishikesh-cert.jpg',
    imgAlt: 'Mukun with her cohort holding her Master Sound Healing certificate',
    caption: 'the day she became a master'
  },
  {
    id: 'kashi',
    order: 2,
    place: 'Kashi',
    region: 'Varanasi · the oldest living city',
    coords: [25.3176, 82.9739],
    season: 'The Fire',
    year: '2023',
    practice: 'Solo pilgrimage · Meditation on the ghats',
    element: 'Agni — fire, transformation, release',
    bowl: 'Sacral',
    lat: '25°19\u2032 N',
    lon: '82°58\u2032 E',
    altitude: '80 m',
    quote: 'I am glad I decided to go alone, without expectation or research.',
    story: 'She went without a list of temples, without a plan. A local led her to Manikarnika Ghat — and the energy kept her there for the rest of the trip. A Masaani man showed her a hidden, deeply spiritual place within the ghat, where she meditated for two hours, intuitively covering herself in ashes. She spent a whole night watching the cremations, Shiva\'s temple before her, napping on a boat in the middle of Ma Ganga.',
    offerings: ['Night on Manikarnika Ghat', 'Meditation covered in ashes', 'Blessings of Ma Ganga & Shiva'],
    img: 'assets/kashi-mukun.jpg',
    imgAlt: 'Mukun in white kurta with red mark on her hand, soft smile',
    caption: 'blessed by ma ganga and shiva'
  },
  {
    id: 'vrindavan',
    order: 3,
    place: 'Vrindavan · Barsana',
    region: 'Braj, Uttar Pradesh',
    coords: [27.5820, 77.7064],
    season: 'The Song',
    year: '2023',
    practice: 'Bhakti · Kirtan',
    element: 'Tulsi — sweetness, longing, the name',
    bowl: 'Heart',
    lat: '27°34\u2032 N',
    lon: '77°42\u2032 E',
    altitude: '170 m',
    quote: 'The heart is an instrument. In Vrindavan, someone else plays it.',
    story: 'Painted in tilak, in a yellow kurta against a wall of turquoise. Evenings of kirtan where no one could tell where one voice ended and another began. She learned that devotion is not intensity — it is a softness that will not let you go.',
    offerings: ['Evening kirtan circles', 'Bhakti sadhana', 'Parikrama walks in Barsana'],
    img: 'assets/vrindavan-barsana.png',
    imgAlt: 'Mukun in a yellow kurta with tilak, turquoise wall of Barsana',
    caption: 'painted, smiling, one with the song'
  },
  {
    id: 'nepal',
    order: 4,
    place: 'Nepal',
    region: 'Kathmandu · Patan · the high country',
    coords: [27.7172, 85.3240],
    season: 'The Bowl is Born',
    year: '2023',
    practice: 'Singing bowls · Tibetan lineage',
    element: 'Bronze — seven metals, seven planets, one hum',
    bowl: 'Solar Plexus',
    lat: '27°43\u2032 N',
    lon: '85°19\u2032 E',
    altitude: '1400 m',
    quote: 'She met the hands that made the bowls she had always played.',
    story: 'Wrapped in white, walking streets where seven metals are still beaten into a single vessel by hand. Prayer flags at every pass, mantras painted on stones. She brought home more than bowls — she brought a lineage, and a promise to carry it carefully.',
    offerings: ['Study with Tibetan masters', 'Bowls sourced from Patan', 'Himalayan sadhana'],
    img: 'assets/nepal-kathmandu.png',
    imgAlt: 'Mukun in a white shawl on a Kathmandu street',
    caption: 'wrapped in white, walking the lineage'
  },
  {
    id: 'bali',
    order: 5,
    place: 'Bali',
    region: 'Indonesia · her first solo',
    coords: [-8.3405, 115.0920],
    season: 'The First Solo',
    year: '2023',
    practice: 'Solo retreat · Sound circle · Breathwork',
    element: 'Frangipani — softness, sea salt, release',
    bowl: 'Sacral',
    lat: '08°20\u2032 S',
    lon: '115°05\u2032 E',
    altitude: '8 m',
    quote: 'कलयुग में सत्युग लाना चाहती हूँ — to bring the Golden Age into this Dark Age.',
    story: 'Rice terraces, warm rain, Ubud mornings that smelled of incense and roasted coffee. The first time she bought her own plane ticket, the first time she walked into a silent dining hall of strangers. In a bamboo sanctuary she sat with other women in white and rang the bowls together, smiling. She came back with freckles and a steadier voice.',
    offerings: ['Solo breathwork retreat', 'Women\'s sound circles', 'Cacao ceremonies'],
    img: 'assets/bali-circle.png',
    imgAlt: 'Mukun with other women in white in a bamboo room, ringing bowls',
    caption: 'कलयुग में सत्युग — by being myself'
  },
  {
    id: 'mirage',
    order: 6,
    place: 'Mirage · Palampur',
    region: 'Himachal forest interlude',
    coords: [32.1109, 76.5361],
    season: 'The Jungle Answers',
    year: '2024',
    practice: 'Silence · Wordless conversation with nature',
    element: 'Deodar — moss, dog-fur, divine coincidence',
    bowl: 'Heart',
    lat: '32°06\u2032 N',
    lon: '76°32\u2032 E',
    altitude: '1220 m',
    quote: 'A dog came running. To my surprise, it was Bagheera — the one I had set an intention to meet that morning.',
    story: 'She asked a question and the divine answered by sending her into the jungle. Conversation flowed with nature without words. Bagheera — a dog she had never met but had set an intention to see — came running and held her gaze until her eyes went teary. A message exchanged. "We parted only to meet again."',
    offerings: ['Forest walking meditation', 'Intention-setting practice', 'Wordless communication'],
    img: 'assets/connection-hug.png',
    imgAlt: 'Mukun in a warm hug, sunlit garden',
    caption: 'trust, hug, repeat'
  },
  {
    id: 'colombia',
    order: 7,
    place: 'Colombia',
    region: 'Cartagena · Medellín',
    coords: [10.3910, -75.4794],
    season: 'The Warmth',
    year: '2024',
    practice: 'Cacao · Plant wisdom · Hermana',
    element: 'Cacao — heart medicine, bitter then sweet',
    bowl: 'Heart',
    lat: '10°23\u2032 N',
    lon: '75°28\u2032 W',
    altitude: '2 m',
    quote: 'Hold on to what is good, even if it is a handful of earth.',
    story: 'Caribbean heat, coral houses, markets with five kinds of mango. She shared cacao on rooftops and learned that hospitality in Spanish has a music even her ear could follow. A continent she had never expected to feel like home.',
    offerings: ['Cacao ceremony', 'Sister circles', 'Slow-travel writing'],
    img: 'assets/colombia-pink.jpg',
    imgAlt: 'Mukun with a friend against a bright pink Cartagena wall',
    caption: 'pink walls, hermana'
  },
  {
    id: 'berlin',
    order: 8,
    place: 'Berlin',
    region: 'Germany · winter circle',
    coords: [52.5200, 13.4050],
    season: 'The Circle Widens',
    year: '2024',
    practice: 'Group ceremonies · Mandala',
    element: 'Brass — sound travels further than language',
    bowl: 'Throat',
    lat: '52°31\u2032 N',
    lon: '13°24\u2032 E',
    altitude: '34 m',
    quote: 'Seven strangers, one mandala. By morning, not strangers.',
    story: 'Brick walls, radiator warmth, women she had never met kneeling around an earth-altar of pomegranates and dried roses. She spoke in English, in Sanskrit, in gestures. The bowls spoke in a language older than any of them.',
    offerings: ['Full-moon ceremonies', 'Seasonal mandala workshops', 'Women\'s sound circles'],
    img: 'assets/mukun-circle-berlin.jpg',
    imgAlt: 'Circle of women around a mandala of singing bowls and flowers',
    caption: 'a mandala built by many hands'
  },
  {
    id: 'paris',
    order: 9,
    place: 'Paris',
    region: 'France — the light of it',
    coords: [48.8566, 2.3522],
    season: 'The Light',
    year: '2024',
    practice: 'Wandering · Journaling',
    element: 'Limestone — the quality of winter light',
    bowl: 'Third Eye',
    lat: '48°51\u2032 N',
    lon: '02°21\u2032 E',
    altitude: '35 m',
    quote: 'Some cities do the teaching without ever being teachers.',
    story: 'A balcony with a view of the Eiffel. Long afternoons in cafés with a journal and a chocolat chaud that never cooled fast enough. A crochet hat, two scarves, miles walked. She wrote more here than she spoke.',
    offerings: ['Solo museum pilgrimages', 'Café journaling', 'Seine-side meditation'],
    img: 'assets/paris-eiffel.jpg',
    imgAlt: 'Mukun on a balcony with the Eiffel Tower behind her',
    caption: 'a balcony, a view, a long afternoon'
  },
  {
    id: 'italy',
    order: 10,
    place: 'Italy',
    region: 'Venice · the canals of jade',
    coords: [45.4408, 12.3155],
    season: 'The Crossing',
    year: '2024',
    practice: 'Walking meditation',
    element: 'Water — two forms, one element',
    bowl: 'Throat',
    lat: '45°26\u2032 N',
    lon: '12°19\u2032 E',
    altitude: '2 m',
    quote: 'Venice is a city that forgot how to be in a hurry.',
    story: 'Canals the color of jade. Bells from a dozen directions, never in sync, always in harmony. She walked in a purple coat for hours, getting pleasantly, intentionally lost.',
    offerings: ['Venice walking meditations', 'Slow pilgrimage', 'Bridge-by-bridge practice'],
    img: 'assets/venice.jpg',
    imgAlt: 'Mukun in a purple coat on a Venice bridge',
    caption: 'jade water, purple coat'
  },
  {
    id: 'switzerland',
    order: 11,
    place: 'Switzerland',
    region: 'Alpine villages · the Italian Alps',
    coords: [46.8182, 8.2275],
    season: 'The Snow Line',
    year: '2024',
    practice: 'Solitude · Cold-exposure breathwork',
    element: 'Snow — the pause inside movement',
    bowl: 'Crown',
    lat: '46°49\u2032 N',
    lon: '08°14\u2032 E',
    altitude: '1200 m',
    quote: 'She had never known a quiet that could be heard.',
    story: 'Villages tucked into valleys, the first real snow of her life underfoot. She learned to breathe differently at altitude, to walk without rushing, to let the mountains set the pace. Some days no practice was needed. The landscape was the practice.',
    offerings: ['Alpine solo time', 'Cold-exposure breathwork', 'Snow sadhana'],
    img: 'assets/italy-snow.jpg',
    imgAlt: 'Mukun in a pink jacket on a snowy alpine road',
    caption: 'first snow, borrowed courage'
  },
  {
    id: 'toronto',
    order: 12,
    place: 'Toronto',
    region: 'Ontario, Canada — and a new home',
    coords: [43.6532, -79.3832],
    season: 'The New Grove',
    year: '2025 — now',
    practice: 'Studio · Community · Rooting',
    element: 'Maple — patience, depth, the long practice',
    bowl: 'Third Eye',
    lat: '43°39\u2032 N',
    lon: '79°23\u2032 W',
    altitude: '76 m',
    quote: 'Across an ocean, the same bowl still knows her hands.',
    story: 'Toronto winters taught her a new kind of stillness. A small studio with warm lamps, a mat, and the bronze bowls she once could barely lift. And — finally — a home beside a partner who keeps coming home to the sound. The work now is to stay. To build. To let people find her here.',
    offerings: ['One-on-one healing sessions', 'Monthly full-moon gatherings', 'Building a life, rooted'],
    img: 'assets/toronto-mukun.png',
    imgAlt: 'Mukun in Toronto, golden light, disco-ball overhead',
    caption: 'the bowl knows her hands, even here'
  }
];

window.JOURNEY = JOURNEY;
